/**
 * Curated pool of popular, well-known MTG cards.
 * No Un-sets, no Attractions, no test prints. Only real printed cards.
 * Each entry: { name, scryfallId }
 * scryfallId is the Scryfall UUID for the most iconic printing.
 */
const CARD_POOL = [
  { name: "Lightning Bolt" },
  { name: "Counterspell" },
  { name: "Swords to Plowshares" },
  { name: "Dark Ritual" },
  { name: "Giant Growth" },
  { name: "Birds of Paradise" },
  { name: "Serra Angel" },
  { name: "Shivan Dragon" },
  { name: "Black Lotus" },
  { name: "Ancestral Recall" },
  { name: "Time Walk" },
  { name: "Mox Pearl" },
  { name: "Sol Ring" },
  { name: "Llanowar Elves" },
  { name: "Wrath of God" },
  { name: "Doom Blade" },
  { name: "Path to Exile" },
  { name: "Thoughtseize" },
  { name: "Snapcaster Mage" },
  { name: "Tarmogoyf" },
  { name: "Jace, the Mind Sculptor" },
  { name: "Liliana of the Veil" },
  { name: "Cryptic Command" },
  { name: "Brainstorm" },
  { name: "Force of Will" },
  { name: "Demonic Tutor" },
  { name: "Necropotence" },
  { name: "Channel" },
  { name: "Fireball" },
  { name: "Disenchant" },
  { name: "Terror" },
  { name: "Naturalize" },
  { name: "Shock" },
  { name: "Murder" },
  { name: "Cancel" },
  { name: "Unsummon" },
  { name: "Pacifism" },
  { name: "Oblivion Ring" },
  { name: "Elvish Mystic" },
  { name: "Goblin Guide" },
  { name: "Monastery Swiftspear" },
  { name: "Delver of Secrets" },
  { name: "Young Pyromancer" },
  { name: "Dark Confidant" },
  { name: "Stoneforge Mystic" },
  { name: "Thalia, Guardian of Thraben" },
  { name: "Noble Hierarch" },
  { name: "Deathrite Shaman" },
  { name: "Collected Company" },
  { name: "Aether Vial" },
  { name: "Chalice of the Void" },
  { name: "Mox Opal" },
  { name: "Arcbound Ravager" },
  { name: "Cranial Plating" },
  { name: "Thoughtcast" },
  { name: "Emrakul, the Aeons Torn" },
  { name: "Ulamog, the Ceaseless Hunger" },
  { name: "Kozilek, Butcher of Truth" },
  { name: "Wurmcoil Engine" },
  { name: "Karn Liberated" },
  { name: "Ugin, the Spirit Dragon" },
  { name: "Nicol Bolas, Dragon-God" },
  { name: "Teferi, Hero of Dominaria" },
  { name: "Nissa, Who Shakes the World" },
  { name: "Chandra, Torch of Defiance" },
  { name: "Gideon, Ally of Zendikar" },
  { name: "Ajani Goldmane" },
  { name: "Garruk Wildspeaker" },
  { name: "Elspeth, Sun's Champion" },
  { name: "Sorin, Vengeful Bloodlord" },
  { name: "Opt" },
  { name: "Fatal Push" },
  { name: "Abrupt Decay" },
  { name: "Assassin's Trophy" },
  { name: "Lightning Helix" },
  { name: "Terminate" },
  { name: "Vindicate" },
  { name: "Maelstrom Pulse" },
  { name: "Supreme Verdict" },
  { name: "Sphinx's Revelation" },
  { name: "Dig Through Time" },
  { name: "Treasure Cruise" },
  { name: "Monastery Mentor" },
  { name: "Gurmag Angler" },
  { name: "Siege Rhino" },
  { name: "Courser of Kruphix" },
  { name: "Sylvan Caryatid" },
  { name: "Restoration Angel" },
  { name: "Blade Splicer" },
  { name: "Kitchen Finks" },
  { name: "Eternal Witness" },
  { name: "Scavenging Ooze" },
  { name: "Tireless Tracker" },
  { name: "Bloodbraid Elf" },
  { name: "Huntmaster of the Fells" },
  { name: "Bonfire of the Damned" },
  { name: "Craterhoof Behemoth" },
  { name: "Avenger of Zendikar" },
  { name: "Sun Titan" },
  { name: "Grave Titan" },
  { name: "Inferno Titan" },
  { name: "Frost Titan" },
  { name: "Primeval Titan" },
  { name: "Baneslayer Angel" },
  { name: "Thundermaw Hellkite" },
  { name: "Stormbreath Dragon" },
  { name: "Glorybringer" },
  { name: "Goldspan Dragon" },
  { name: "Elder Gargaroth" },
  { name: "Questing Beast" },
  { name: "Bonecrusher Giant" },
  { name: "Brazen Borrower" },
  { name: "Murderous Rider" },
  { name: "Lovestruck Beast" },
  { name: "Embercleave" },
  { name: "The Great Henge" },
  { name: "Edgewall Innkeeper" },
  { name: "Gilded Goose" },
  { name: "Oko, Thief of Crowns" },
  { name: "Uro, Titan of Nature's Wrath" },
  { name: "Kroxa, Titan of Death's Hunger" },
  { name: "Omnath, Locus of Creation" },
  { name: "Ragavan, Nimble Pilferer" },
  { name: "Dragon's Rage Channeler" },
  { name: "Unholy Heat" },
  { name: "Prismatic Ending" },
  { name: "Solitude" },
  { name: "Fury" },
  { name: "Endurance" },
  { name: "Grief" },
  { name: "Subtlety" },
  { name: "Murktide Regent" },
  { name: "Ledger Shredder" },
  { name: "Fable of the Mirror-Breaker" },
  { name: "The Wandering Emperor" },
  { name: "Sheoldred, the Apocalypse" },
  { name: "Atraxa, Grand Unifier" },
  { name: "Raffine, Scheming Seer" },
  { name: "Fabled Passage" },
  { name: "Prismatic Vista" },
  { name: "Flooded Strand" },
  { name: "Polluted Delta" },
  { name: "Windswept Heath" },
  { name: "Wooded Foothills" },
  { name: "Bloodstained Mire" },
  { name: "Scalding Tarn" },
  { name: "Misty Rainforest" },
  { name: "Verdant Catacombs" },
  { name: "Arid Mesa" },
  { name: "Marsh Flats" },
  { name: "Command Tower" },
  { name: "Cavern of Souls" },
  { name: "Ancient Tomb" },
  { name: "Strip Mine" },
  { name: "Wasteland" },
  { name: "Field of the Dead" },
  { name: "Urza's Saga" },
  { name: "Mana Crypt" },
  { name: "Mana Vault" },
  { name: "Sensei's Divining Top" },
  { name: "Skullclamp" },
  { name: "Umezawa's Jitte" },
  { name: "Batterskull" },
  { name: "Sword of Fire and Ice" },
  { name: "Sword of Feast and Famine" },
  { name: "Lightning Greaves" },
  { name: "Swiftfoot Boots" },
  { name: "Thought Vessel" },
  { name: "Mind Stone" },
  { name: "Arcane Signet" },
  { name: "Cyclonic Rift" },
  { name: "Rhystic Study" },
  { name: "Smothering Tithe" },
  { name: "Dockside Extortionist" },
  { name: "Fierce Guardianship" },
  { name: "Deflecting Swat" },
  { name: "Jeska's Will" },
  { name: "Mystic Remora" },
  { name: "Esper Sentinel" },
  { name: "Beast Within" },
  { name: "Chaos Warp" },
  { name: "Generous Gift" },
  { name: "Anguished Unmaking" },
  { name: "Dovin's Veto" },
  { name: "Growth Spiral" },
  { name: "Rampant Growth" },
  { name: "Cultivate" },
  { name: "Kodama's Reach" },
  { name: "Explore" },
  { name: "Farseek" },
  { name: "Ponder" },
  { name: "Preordain" },
  { name: "Serum Visions" },
  { name: "Gitaxian Probe" },
  { name: "Faithless Looting" },
  { name: "Entomb" },
  { name: "Reanimate" },
  { name: "Animate Dead" },
  { name: "Exhume" },
  { name: "Living Death" },
  { name: "Damnation" },
  { name: "Toxic Deluge" },
  { name: "Vandalblast" },
  { name: "Blasphemous Act" },
  { name: "Austere Command" },
  { name: "Merciless Eviction" },
  { name: "Farewell" },
  { name: "Rite of Flame" },
  { name: "Pyretic Ritual" },
  { name: "Manamorphose" },
  { name: "Grapeshot" },
  { name: "Tendrils of Agony" },
  { name: "Empty the Warrens" },
  { name: "Past in Flames" },
  { name: "Gifts Ungiven" },
  { name: "Fact or Fiction" },
  { name: "Mulldrifter" },
  { name: "Consecrated Sphinx" },
  { name: "Jin-Gitaxias, Core Augur" },
  { name: "Vorinclex, Voice of Hunger" },
  { name: "Elesh Norn, Grand Cenobite" },
  { name: "Sheoldred, Whispering One" },
  { name: "Urabrask the Hidden" },
  { name: "Griselbrand" },
  { name: "Aetherling" },
  { name: "Thragtusk" },
  { name: "Geist of Saint Traft" },
  { name: "Lingering Souls" },
  { name: "Spectral Procession" },
  { name: "Bitterblossom" },
  { name: "Doubling Season" },
  { name: "Parallel Lives" },
  { name: "Anointed Procession" },
  { name: "Phyrexian Arena" },
  { name: "Sylvan Library" },
  { name: "Scroll Rack" },
  { name: "Land Tax" },
  { name: "Enlightened Tutor" },
  { name: "Mystical Tutor" },
  { name: "Vampiric Tutor" },
  { name: "Worldly Tutor" },
  { name: "Gamble" },
  { name: "Green Sun's Zenith" },
  { name: "Chord of Calling" },
  { name: "Natural Order" },
  { name: "Tooth and Nail" },
  { name: "Genesis Wave" },
  { name: "Torment of Hailfire" },
  { name: "Exsanguinate" },
  { name: "Comet Storm" },
  { name: "Finale of Devastation" },
  { name: "Villainous Wealth" },
  { name: "Mox Sapphire" },
  { name: "Mox Jet" },
  { name: "Mox Ruby" },
  { name: "Mox Emerald" },
  { name: "Time Vault" },
  { name: "Timetwister" },
  { name: "Library of Alexandria" },
  { name: "Bazaar of Baghdad" },
  { name: "Mishra's Workshop" },
  { name: "The Tabernacle at Pendrell Vale" },
  { name: "Gaea's Cradle" },
  { name: "Tolarian Academy" },
  { name: "Serra's Sanctum" },
  { name: "Karakas" },
  { name: "Rishadan Port" },
  { name: "Maze of Ith" },
  { name: "Dark Depths" },
  { name: "Thespian's Stage" },
  { name: "Urborg, Tomb of Yawgmoth" },
  { name: "Cabal Coffers" },
  { name: "Nykthos, Shrine to Nyx" },
  { name: "Boseiju, Who Shelters All" },
  { name: "Eiganjo Castle" },
  { name: "Mutavault" },
  { name: "Celestial Colonnade" },
  { name: "Creeping Tar Pit" },
  { name: "Raging Ravine" },
  { name: "Inkmoth Nexus" },
  { name: "Blinkmoth Nexus" },
  { name: "Mishra's Factory" },
  { name: "Treetop Village" },
  { name: "Ghost Quarter" },
  { name: "Tectonic Edge" },
  { name: "Blast Zone" },
  { name: "Reliquary Tower" },
  { name: "Lotus Petal" },
  { name: "Chrome Mox" },
  { name: "Mox Diamond" },
  { name: "Lion's Eye Diamond" },
  { name: "Black Vise" },
  { name: "Winter Orb" },
  { name: "Smokestack" },
  { name: "Tangle Wire" },
  { name: "Trinisphere" },
  { name: "Thorn of Amethyst" },
  { name: "Null Rod" },
  { name: "Pithing Needle" },
  { name: "Grafdigger's Cage" },
  { name: "Torpor Orb" },
  { name: "Relic of Progenitus" },
  { name: "Tormod's Crypt" },
  { name: "Nihil Spellbomb" },
  { name: "Engineered Explosives" },
  { name: "Oblivion Stone" },
  { name: "Nevinyrral's Disk" },
  { name: "All Is Dust" },
  { name: "Karn, the Great Creator" },
  { name: "Walking Ballista" },
  { name: "Hangarback Walker" },
  { name: "Steel Overseer" },
  { name: "Metalworker" },
  { name: "Solemn Simulacrum" },
  { name: "Platinum Angel" },
  { name: "Blightsteel Colossus" },
  { name: "Myr Battlesphere" },
  { name: "Sundering Titan" },
  { name: "Kozilek, the Great Distortion" },
  { name: "Ulamog, the Infinite Gyre" },
  { name: "Thought-Knot Seer" },
  { name: "Reality Smasher" },
  { name: "Baleful Strix" },
  { name: "Shardless Agent" },
  { name: "Leovold, Emissary of Trest" },
  { name: "Notion Thief" },
  { name: "Narset, Parter of Veils" },
  { name: "Teferi, Time Raveler" },
  { name: "Wrenn and Six" },
  { name: "Nahiri, the Harbinger" },
  { name: "Daretti, Scrap Savant" },
  { name: "Kolaghan's Command" },
  { name: "Archmage's Charm" },
  { name: "Expressive Iteration" },
  { name: "Mother of Runes" },
  { name: "Giver of Runes" },
  { name: "Champion of the Parish" },
  { name: "Thraben Inspector" },
  { name: "Luminarch Aspirant" },
  { name: "Leonin Arbiter" },
  { name: "Aven Mindcensor" },
  { name: "Flickerwisp" },
  { name: "Palace Jailer" },
  { name: "Recruiter of the Guard" },
  { name: "Ranger-Captain of Eos" },
  { name: "Hero of Bladehold" },
  { name: "Mirran Crusader" },
  { name: "Brimaz, King of Oreskos" },
  { name: "Lyra Dawnbringer" },
  { name: "Reveillark" },
  { name: "Elesh Norn, Mother of Machines" },
  { name: "Day of Judgment" },
  { name: "Terminus" },
  { name: "Council's Judgment" },
  { name: "Armageddon" },
  { name: "Skyclave Apparition" },
  { name: "Rest in Peace" },
  { name: "Stony Silence" },
  { name: "Authority of the Consuls" },
  { name: "True-Name Nemesis" },
  { name: "Vendilion Clique" },
  { name: "Phantasmal Image" },
  { name: "Deceiver Exarch" },
  { name: "Splinter Twin" },
  { name: "Thassa's Oracle" },
  { name: "Laboratory Maniac" },
  { name: "Hullbreacher" },
  { name: "Remand" },
  { name: "Mana Leak" },
  { name: "Mana Drain" },
  { name: "Spell Pierce" },
  { name: "Flusterstorm" },
  { name: "Swan Song" },
  { name: "Negate" },
  { name: "Daze" },
  { name: "Stifle" },
  { name: "Time Warp" },
  { name: "High Tide" },
  { name: "Brain Freeze" },
  { name: "Show and Tell" },
  { name: "Omniscience" },
  { name: "Tinker" },
  { name: "Windfall" },
  { name: "Wheel of Fortune" },
  { name: "Spreading Seas" },
  { name: "Treachery" },
  { name: "Opposition" },
  { name: "Back to Basics" },
  { name: "Hypnotic Specter" },
  { name: "Pack Rat" },
  { name: "Dauthi Voidwalker" },
  { name: "Bloodghast" },
  { name: "Phyrexian Obliterator" },
  { name: "Vampire Nighthawk" },
  { name: "Gray Merchant of Asphodel" },
  { name: "Kokusho, the Evening Star" },
  { name: "Massacre Wurm" },
  { name: "Yawgmoth, Thran Physician" },
  { name: "Cabal Therapy" },
  { name: "Duress" },
  { name: "Inquisition of Kozilek" },
  { name: "Hymn to Tourach" },
  { name: "Dismember" },
  { name: "Go for the Throat" },
  { name: "Infernal Grasp" },
  { name: "Snuff Out" },
  { name: "Buried Alive" },
  { name: "Yawgmoth's Will" },
  { name: "Recurring Nightmare" },
  { name: "The Meathook Massacre" },
  { name: "Goblin Lackey" },
  { name: "Goblin Piledriver" },
  { name: "Goblin Warchief" },
  { name: "Goblin Matron" },
  { name: "Siege-Gang Commander" },
  { name: "Krenko, Mob Boss" },
  { name: "Kiki-Jiki, Mirror Breaker" },
  { name: "Zealous Conscripts" },
  { name: "Abrade" },
  { name: "Chain Lightning" },
  { name: "Lava Spike" },
  { name: "Eidolon of the Great Revel" },
  { name: "Seasoned Pyromancer" },
  { name: "Through the Breach" },
  { name: "Sneak Attack" },
  { name: "Blood Moon" },
  { name: "Pyroblast" },
  { name: "Red Elemental Blast" },
  { name: "Underworld Breach" },
  { name: "Wild Nacatl" },
  { name: "Nimble Mongoose" },
  { name: "Fauna Shaman" },
  { name: "Survival of the Fittest" },
  { name: "Birthing Pod" },
  { name: "Utopia Sprawl" },
  { name: "Wild Growth" },
  { name: "Carpet of Flowers" },
  { name: "Wall of Roots" },
  { name: "Priest of Titania" },
  { name: "Elvish Archdruid" },
  { name: "Heritage Druid" },
  { name: "Nettle Sentinel" },
  { name: "Quirion Ranger" },
  { name: "Arbor Elf" },
  { name: "Reclamation Sage" },
  { name: "Acidic Slime" },
  { name: "Thrun, the Last Troll" },
  { name: "Carnage Tyrant" },
  { name: "Woodfall Primus" },
  { name: "Hornet Queen" },
  { name: "Krosan Grip" },
  { name: "Veil of Summer" },
  { name: "Heroic Intervention" },
  { name: "Berserk" },
  { name: "Regrowth" },
  { name: "Life from the Loam" },
  { name: "Crucible of Worlds" },
  { name: "Ramunap Excavator" },
  { name: "Oracle of Mul Daya" },
  { name: "Azusa, Lost but Seeking" },
  { name: "Exploration" },
  { name: "Nature's Lore" },
  { name: "Scapeshift" },
  { name: "Valakut, the Molten Pinnacle" },
  { name: "Food Chain" },
  { name: "Allosaurus Shepherd" },
  { name: "Leyline of the Void" },
  { name: "Ensnaring Bridge" },
  { name: "Isochron Scepter" },
  { name: "Grim Monolith" },
  { name: "Basalt Monolith" },
  { name: "Thran Dynamo" },
  { name: "Gilded Lotus" },
  { name: "Coalition Relic" },
  { name: "Sword of Light and Shadow" },
  { name: "Basilisk Collar" },
  { name: "Shadowspear" },
  { name: "Painter's Servant" },
  { name: "Grindstone" },
  { name: "Altar of Dementia" },
  { name: "Phyrexian Altar" },
  { name: "Ashnod's Altar" },
  { name: "Aetherflux Reservoir" },
  { name: "Bolas's Citadel" },
  { name: "Panharmonicon" },
  { name: "Aluren" },
  { name: "Gaddock Teeg" },
  { name: "Knight of the Reliquary" },
  { name: "Voice of Resurgence" },
  { name: "Sigarda, Host of Herons" },
  { name: "Mirari's Wake" },
  { name: "Eladamri's Call" },
  { name: "Temple Garden" },
  { name: "Hallowed Fountain" },
  { name: "Watery Grave" },
  { name: "Blood Crypt" },
  { name: "Stomping Ground" },
  { name: "Breeding Pool" },
  { name: "Godless Shrine" },
  { name: "Sacred Foundry" },
  { name: "Overgrown Tomb" },
  { name: "Steam Vents" },
  { name: "Underground Sea" },
  { name: "Volcanic Island" },
  { name: "Tropical Island" },
  { name: "Tundra" },
  { name: "Bayou" },
  { name: "Badlands" },
  { name: "Taiga" },
  { name: "Plateau" },
  { name: "Scrubland" },
  { name: "City of Brass" },
  { name: "Mana Confluence" },
  { name: "Reflecting Pool" },
  { name: "Phyrexian Tower" },
  { name: "Volrath's Stronghold" },
  { name: "Academy Ruins" },
  { name: "Gavony Township" },
  { name: "Lord of Atlantis" },
  { name: "Silvergill Adept" },
  { name: "Gravecrawler" },
  { name: "Animar, Soul of Elements" },
  { name: "Muldrotha, the Gravetide" },
  { name: "Atraxa, Praetors' Voice" },
  { name: "Breya, Etherium Shaper" },
  { name: "Korvold, Fae-Cursed King" },
  { name: "Prossh, Skyraider of Kher" },
  { name: "Maelstrom Wanderer" },
  { name: "Edgar Markov" },
  { name: "The Ur-Dragon" },
  { name: "Kenrith, the Returned King" },
  { name: "Yuriko, the Tiger's Shadow" },
  { name: "Brago, King Eternal" },
  { name: "Zur the Enchanter" },
  { name: "Kaalia of the Vast" },
  { name: "Meren of Clan Nel Toth" },
  { name: "Yarok, the Desecrated" },
  { name: "Urza, Lord High Artificer" },
  { name: "Purphoros, God of the Forge" },
  { name: "Thassa, God of the Sea" },
  { name: "Erebos, God of the Dead" },
  { name: "Heliod, Sun-Crowned" },
  { name: "Xenagos, God of Revels" },
  { name: "Grim Lavamancer" },
  { name: "Anger of the Gods" },
  { name: "Sulfuric Vortex" },
  { name: "Price of Progress" },
  { name: "Light Up the Stage" },
  { name: "Hazoret the Fervent" },
  { name: "Rekindling Phoenix" },
  { name: "Soul-Scar Mage" },
  { name: "Living End" },
  { name: "Force of Negation" },
  { name: "Force of Vigor" },
  { name: "Pact of Negation" },
  { name: "Niv-Mizzet, Parun" },
  { name: "Hydroid Krasis" },
  { name: "Spell Queller" },
  { name: "Dragonlord Ojutai" },
  { name: "Pernicious Deed" },
  { name: "Ancient Grudge" },
  { name: "Drown in the Loch" },
  { name: "Cruel Ultimatum" },
  { name: "Edric, Spymaster of Trest" },
  { name: "Mantis Rider" },
  { name: "Mayhem Devil" },
  { name: "Selvala, Heart of the Wilds" },
  { name: "Aurelia, the Warleader" },
  { name: "Queen Marchesa" },
  { name: "Kess, Dissident Mage" },
  { name: "Tasigur, the Golden Fang" },
  { name: "Omnath, Locus of Mana" },
  { name: "Academy Rector" },
  { name: "Imperial Recruiter" },
  { name: "Etali, Primal Storm" },
  { name: "Torrential Gearhulk" },
  { name: "Hero's Downfall" },
  { name: "Shriekmaw" },
  { name: "Ravenous Chupacabra" },
  { name: "Razaketh, the Foulblooded" },
  { name: "Mikaeus, the Unhallowed" },
  { name: "Archon of Cruelty" },
  { name: "Grave Pact" },
  { name: "Tragic Slip" },
  { name: "Deadly Rollick" },
  { name: "Night's Whisper" },
  { name: "Sign in Blood" },
  { name: "Read the Bones" },
  { name: "Ad Nauseam" },
  { name: "Diabolic Intent" },
  { name: "Imperial Seal" },
  { name: "Opposition Agent" },
  { name: "Scion of the Ur-Dragon" },
];

// Deduplicate by name
const seen = new Set();
const UNIQUE_CARD_POOL = CARD_POOL.filter(c => {
  if (seen.has(c.name)) return false;
  seen.add(c.name);
  return true;
});
