/**
 * Curated pool of popular, well-known MTG cards.
 * No Un-sets, no Attractions, no test prints. Only real printed cards.
 * Each entry: { name, scryfallId }
 * scryfallId is the Scryfall UUID for the most iconic printing.
 */
const CARD_POOL = [
  { name: "Lightning Bolt" },
  { name: "Counterspell" },
  { name: "Swords to Plowshares" },
  { name: "Dark Ritual" },
  { name: "Giant Growth" },
  { name: "Birds of Paradise" },
  { name: "Serra Angel" },
  { name: "Shivan Dragon" },
  { name: "Black Lotus" },
  { name: "Ancestral Recall" },
  { name: "Time Walk" },
  { name: "Mox Pearl" },
  { name: "Sol Ring" },
  { name: "Llanowar Elves" },
  { name: "Wrath of God" },
  { name: "Doom Blade" },
  { name: "Path to Exile" },
  { name: "Thoughtseize" },
  { name: "Snapcaster Mage" },
  { name: "Tarmogoyf" },
  { name: "Jace, the Mind Sculptor" },
  { name: "Liliana of the Veil" },
  { name: "Cryptic Command" },
  { name: "Brainstorm" },
  { name: "Force of Will" },
  { name: "Demonic Tutor" },
  { name: "Necropotence" },
  { name: "Channel" },
  { name: "Fireball" },
  { name: "Disenchant" },
  { name: "Terror" },
  { name: "Naturalize" },
  { name: "Shock" },
  { name: "Murder" },
  { name: "Cancel" },
  { name: "Unsummon" },
  { name: "Pacifism" },
  { name: "Oblivion Ring" },
  { name: "Elvish Mystic" },
  { name: "Goblin Guide" },
  { name: "Monastery Swiftspear" },
  { name: "Delver of Secrets" },
  { name: "Young Pyromancer" },
  { name: "Dark Confidant" },
  { name: "Stoneforge Mystic" },
  { name: "Thalia, Guardian of Thraben" },
  { name: "Noble Hierarch" },
  { name: "Deathrite Shaman" },
  { name: "Collected Company" },
  { name: "Aether Vial" },
  { name: "Chalice of the Void" },
  { name: "Mox Opal" },
  { name: "Arcbound Ravager" },
  { name: "Cranial Plating" },
  { name: "Thoughtcast" },
  { name: "Emrakul, the Aeons Torn" },
  { name: "Ulamog, the Ceaseless Hunger" },
  { name: "Kozilek, Butcher of Truth" },
  { name: "Wurmcoil Engine" },
  { name: "Karn Liberated" },
  { name: "Ugin, the Spirit Dragon" },
  { name: "Nicol Bolas, Dragon-God" },
  { name: "Teferi, Hero of Dominaria" },
  { name: "Nissa, Who Shakes the World" },
  { name: "Chandra, Torch of Defiance" },
  { name: "Gideon, Ally of Zendikar" },
  { name: "Ajani Goldmane" },
  { name: "Garruk Wildspeaker" },
  { name: "Elspeth, Sun's Champion" },
  { name: "Sorin, Vengeful Bloodlord" },
  { name: "Opt" },
  { name: "Fatal Push" },
  { name: "Abrupt Decay" },
  { name: "Assassin's Trophy" },
  { name: "Lightning Helix" },
  { name: "Terminate" },
  { name: "Vindicate" },
  { name: "Maelstrom Pulse" },
  { name: "Supreme Verdict" },
  { name: "Sphinx's Revelation" },
  { name: "Dig Through Time" },
  { name: "Treasure Cruise" },
  { name: "Monastery Mentor" },
  { name: "Gurmag Angler" },
  { name: "Siege Rhino" },
  { name: "Courser of Kruphix" },
  { name: "Sylvan Caryatid" },
  { name: "Restoration Angel" },
  { name: "Blade Splicer" },
  { name: "Kitchen Finks" },
  { name: "Eternal Witness" },
  { name: "Scavenging Ooze" },
  { name: "Tireless Tracker" },
  { name: "Bloodbraid Elf" },
  { name: "Huntmaster of the Fells" },
  { name: "Bonfire of the Damned" },
  { name: "Craterhoof Behemoth" },
  { name: "Avenger of Zendikar" },
  { name: "Sun Titan" },
  { name: "Grave Titan" },
  { name: "Inferno Titan" },
  { name: "Frost Titan" },
  { name: "Primeval Titan" },
  { name: "Baneslayer Angel" },
  { name: "Thundermaw Hellkite" },
  { name: "Stormbreath Dragon" },
  { name: "Glorybringer" },
  { name: "Goldspan Dragon" },
  { name: "Elder Gargaroth" },
  { name: "Questing Beast" },
  { name: "Bonecrusher Giant" },
  { name: "Brazen Borrower" },
  { name: "Murderous Rider" },
  { name: "Lovestruck Beast" },
  { name: "Embercleave" },
  { name: "The Great Henge" },
  { name: "Edgewall Innkeeper" },
  { name: "Gilded Goose" },
  { name: "Oko, Thief of Crowns" },
  { name: "Uro, Titan of Nature's Wrath" },
  { name: "Kroxa, Titan of Death's Hunger" },
  { name: "Omnath, Locus of Creation" },
  { name: "Ragavan, Nimble Pilferer" },
  { name: "Dragon's Rage Channeler" },
  { name: "Unholy Heat" },
  { name: "Prismatic Ending" },
  { name: "Solitude" },
  { name: "Fury" },
  { name: "Endurance" },
  { name: "Grief" },
  { name: "Subtlety" },
  { name: "Murktide Regent" },
  { name: "Ledger Shredder" },
  { name: "Fable of the Mirror-Breaker" },
  { name: "The Wandering Emperor" },
  { name: "Sheoldred, the Apocalypse" },
  { name: "Atraxa, Grand Unifier" },
  { name: "Raffine, Scheming Seer" },
  { name: "Fabled Passage" },
  { name: "Prismatic Vista" },
  { name: "Flooded Strand" },
  { name: "Polluted Delta" },
  { name: "Windswept Heath" },
  { name: "Wooded Foothills" },
  { name: "Bloodstained Mire" },
  { name: "Scalding Tarn" },
  { name: "Misty Rainforest" },
  { name: "Verdant Catacombs" },
  { name: "Arid Mesa" },
  { name: "Marsh Flats" },
  { name: "Command Tower" },
  { name: "Cavern of Souls" },
  { name: "Ancient Tomb" },
  { name: "Strip Mine" },
  { name: "Wasteland" },
  { name: "Field of the Dead" },
  { name: "Urza's Saga" },
  { name: "Mana Crypt" },
  { name: "Mana Vault" },
  { name: "Sensei's Divining Top" },
  { name: "Skullclamp" },
  { name: "Umezawa's Jitte" },
  { name: "Batterskull" },
  { name: "Sword of Fire and Ice" },
  { name: "Sword of Feast and Famine" },
  { name: "Lightning Greaves" },
  { name: "Swiftfoot Boots" },
  { name: "Thought Vessel" },
  { name: "Mind Stone" },
  { name: "Arcane Signet" },
  { name: "Cyclonic Rift" },
  { name: "Rhystic Study" },
  { name: "Smothering Tithe" },
  { name: "Dockside Extortionist" },
  { name: "Fierce Guardianship" },
  { name: "Deflecting Swat" },
  { name: "Jeska's Will" },
  { name: "Mystic Remora" },
  { name: "Esper Sentinel" },
  { name: "Swords to Plowshares" },
  { name: "Beast Within" },
  { name: "Chaos Warp" },
  { name: "Generous Gift" },
  { name: "Anguished Unmaking" },
  { name: "Dovin's Veto" },
  { name: "Growth Spiral" },
  { name: "Rampant Growth" },
  { name: "Cultivate" },
  { name: "Kodama's Reach" },
  { name: "Explore" },
  { name: "Farseek" },
  { name: "Ponder" },
  { name: "Preordain" },
  { name: "Serum Visions" },
  { name: "Gitaxian Probe" },
  { name: "Faithless Looting" },
  { name: "Entomb" },
  { name: "Reanimate" },
  { name: "Animate Dead" },
  { name: "Exhume" },
  { name: "Living Death" },
  { name: "Damnation" },
  { name: "Toxic Deluge" },
  { name: "Cyclonic Rift" },
  { name: "Vandalblast" },
  { name: "Blasphemous Act" },
  { name: "Austere Command" },
  { name: "Merciless Eviction" },
  { name: "Farewell" },
  { name: "Rite of Flame" },
  { name: "Pyretic Ritual" },
  { name: "Manamorphose" },
  { name: "Grapeshot" },
  { name: "Tendrils of Agony" },
  { name: "Empty the Warrens" },
  { name: "Past in Flames" },
  { name: "Gifts Ungiven" },
  { name: "Fact or Fiction" },
  { name: "Mulldrifter" },
  { name: "Consecrated Sphinx" },
  { name: "Jin-Gitaxias, Core Augur" },
  { name: "Vorinclex, Voice of Hunger" },
  { name: "Elesh Norn, Grand Cenobite" },
  { name: "Sheoldred, Whispering One" },
  { name: "Urabrask the Hidden" },
  { name: "Griselbrand" },
  { name: "Aetherling" },
  { name: "Thragtusk" },
  { name: "Restoration Angel" },
  { name: "Geist of Saint Traft" },
  { name: "Lingering Souls" },
  { name: "Spectral Procession" },
  { name: "Bitterblossom" },
  { name: "Doubling Season" },
  { name: "Parallel Lives" },
  { name: "Anointed Procession" },
  { name: "Phyrexian Arena" },
  { name: "Sylvan Library" },
  { name: "Sensei's Divining Top" },
  { name: "Scroll Rack" },
  { name: "Land Tax" },
  { name: "Enlightened Tutor" },
  { name: "Mystical Tutor" },
  { name: "Vampiric Tutor" },
  { name: "Worldly Tutor" },
  { name: "Gamble" },
  { name: "Green Sun's Zenith" },
  { name: "Chord of Calling" },
  { name: "Natural Order" },
  { name: "Tooth and Nail" },
  { name: "Genesis Wave" },
  { name: "Torment of Hailfire" },
  { name: "Exsanguinate" },
  { name: "Comet Storm" },
  { name: "Finale of Devastation" },
  { name: "Villainous Wealth" },
];

// Deduplicate by name
const seen = new Set();
const UNIQUE_CARD_POOL = CARD_POOL.filter(c => {
  if (seen.has(c.name)) return false;
  seen.add(c.name);
  return true;
});
